apiVersion: v1
kind: Pod
metadata:
  name: pod-pv
spec:
  containers:
  - name: nginx-conatiner
    image: nginx:latest
    volumeMounts:
    - mountPath: /volume-dentro-do-container
      name: primeiro-volumes
  - name: jenkins-conatiner
    image: jenkins:latest
    volumeMounts:
    - mountPath: /volume-dentro-do-container
      name: primeiro-volume
  volumes:
  - name: primeiro-pv
    path: /c/caminho/da/pasta
    type: Directory
