apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: prineiro-pod
spec:
  containers:
  - name: container-pod-1
    image: nginx:latest
    ports:
    - containerPort: 80



