apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  selector:
    app: prineiro-pod
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
#     targetPort: 80 opicional se for a mesma porta
